### ISSUE TITLE
Вопросы по task5

### ISSUE THREAD

**Issue by arinarudevich** [arinarudevich/UP#4]
@AntonGrigoriev
Здрасьте, вы что-то не отвечаете на почте, пишу сюда.

~Вызов addPhotoPost({description: ‘description’, ...})  - добавляет фото пост в массив фото постов и отображает новый фото пост в списке в браузере 
!!!(в нужную позицию в соответствии с условиями сортировки).

Эта функция должна создавать новый пост, то есть он будет самым последним. Получается его просто нужно отображать в ленте, как самый новый, так? Это и имеется в виду под сортировкой?

 ~Вызов removePhotoPost(id) - удаляет фото пост из массива фото постов и удаляет фото пост из списка в браузере (если он отображается). 

Последнее уточнение в скобках относится к удалению из браузера или вообще? Должна ли функция уметь удалять объекты, которые не отображаются (пользователь ведь не знает о их существовании, зачем ему их удалять)

И хотелось бы уточнить, влияет ли на оценку отсутствие пункта с фильтром по автору, если select не используется

**Comment by batist73** [comment]
@arinarudevich @slawiko

Извиняюсь за задержку.

**addPhotoPost:**
* Да, под сортировкой подразумевается именно сортировка по времени создания поста. Но учтите, что фильтры также должны применяться на ходу.

**removePhotoPost:**
* Уточение в скобках относится к браузеру. То есть, если пост в данный момент времени отображается на экране, то полсе удаления он должен пропасть.
* По поводу способностей функции, я бы сказал, что функция должна уметь удалять посты, даже если они не отображаются на странице в текущий момент времени. С одной стороны это действительно не совсем реальный случай, ибо удаление в будущем будет происходить по нажатию кнопки на странице. Но с другой стороны валидировать удаляемый пост на предмет видимости тоже специфично.

**select:**
* Нет, не влияет. Этот пункт только для тех работ, где фильтр по авторам устроен в виде выпадающего списка с перечнем имён.

**Comment by arinarudevich** [comment]
Ну, а раз так вышло, что функция remove вызывает функцию удаления поста из
браузера, а если там его нет, то все летит к чертям, можно так и оставить,
ведь такой ошибки произойти не сможет?

**Comment by batist73** [comment]
@arinarudevich 

А почему летит? :) На самом деле такой случай стоит обработать, чтобы это ни к чему неожиданному не приводило.

**Comment by arinarudevich** [comment]
Потому что remove должна еще подгружать один пост, я это сделала через
get(кол.постов на странице, 1), чтобы добавить следующий пост после
сортировки в массиве (в get она есть). Что происходит: 1) удаляем пост из
массива, 2) удаляем из браузера, 3)подгружаем следующий пост.
Ну и она подгружает тот пост, который уже есть на странице
Заметила проблему уже в конце и пока не исправляла, в надежде, что не нужно
будет :(

**Comment by batist73** [comment]
@arinarudevich 

Ага, понял вас. Тогда действительно можно встроить проверку на то, отображается ли пост на странице. И если не отображается, то удалять только из массива.

**Comment by arinarudevich** [comment]
(((

**Comment by arinarudevich** [comment]
@AntonGrigoriev
На самом деле, я уже много чего переосмыслила... Вы еще не проверяли задание? Можно пока не смотреть мой код, чтобы потом сразу исправленное проверить?

**Comment by batist73** [comment]
@arinarudevich 

Ещё не смотрел, смело исправляйте.

**Comment by arinarudevich** [comment]
Класс)

**Comment by arinarudevich** [comment]
@AntonGrigoriev 
Исправлено

**Comment by batist73** [comment]
@arinarudevich 

Тогда можете закрыть это ишью.
