### ISSUE TITLE
Уточнение функции remove

### ISSUE THREAD

**Issue by arinarudevich** [arinarudevich/UP#5]
@AntonGrigoriev
Добрый день! 
Возник вопрос по поводу удаления постов. Вот что написано в тз:

 Авторизованный пользователь может удалить свой фото пост. После нажатия на кнопку 
удаления поста пользователь должен подтвердить, что он хочет удалить фото пост. 
Удаленные посты не удаляются, но помечаются как удаленные, и больше не отображаются 
в ленте фото постов​.

То есть возможности удалить из памяти созданный пост у пользователя нет?  И все посты должны оставаться в localstorage(на момент 6 задания), даже если они не отображаются? А функции для удаления из памяти были прописаны не для пользователя..

**Comment by arinarudevich** [comment]
@AntonGrigoriev
@slawiko

Добрый день..
Вопрос с удалением открыт. Только он перекочевал в коллективное недовольство тз. Вот что написано в 5 таске:
"Вызов removePhotoPost(id) - удаляет фото пост из массива фото постов и удаляет фото пост из списка в браузере (если он отображается)."
То есть в предыдущих заданиях предусматривалось удаление из памяти, а на шестой оно резко превратилось в "пометить как удаленный". Если подумать со стороны пользователя, где-то в памяти останутся все посты, которые он создавал. Ну это же кошмар. Можно игнорировать этот момент?

**Comment by batist73** [comment]
@arinarudevich 

Извиняемся, почему-то не увидели это ишью в своё время. Наверное, вопрос уже не в силе, но всё же ответим. В тз действительно совершенно зря написали про отсутствие физического удаления постов. Но это относится исключительно к базе данных, то бишь уже к последней лабораторной работе. Во всех работах до неё вы можете спокойно удалять посты, как из памяти, так и из временных хранилищ.

**Comment by arinarudevich** [comment]
Да, немного не вовремя, но все равно спасибо ;)
