### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by slawiko** [arinarudevich/UP#7]
@arinarudevich 

### createPhotopost
- совершенно нечитаемая функция. Ее стоило разбить на много маленьких функций. Или же воспользоваться [шаблонизированными строками](http://learn.javascript.ru/es-string#строки-шаблоны), и писать html в них.
- не нашел метода редактирования фотопоста. Добавите - повысим отметку

**Comment by arinarudevich** [comment]
@slawiko
Добрый день)
createPhotopost я уже менять не буду, это стоило сделать вовремя
По поводу редактирования, проблема в том, что такс был сделан два месяца назад, и я уже не помню, было ли все написано в нужный срок. Мне казалось, что функции были прописаны все, не только create и delete. И, кажется, в коммите "completed task5, fixed modules" метод edit есть. Не знаю, проходил ли он по дэдлайнам, но с ними в нашей группе как-то скользко все было))) Впоследствии я вообще нашла много багов в этом модуле, которые исправляла.

**Comment by slawiko** [comment]
на тэге `task5` метода не нашел, не обессудьте :)
